using System;
using ClassLib_A4;
/*Create a class Account having private instance member Id, Name Balanceamt. Id should be generated by application. Create method deposit who’s job is to increase Balanceamtby the amout deposited by account holder. Create method withdraw who’s job is to decrease Balanceamt by the amount  withdrawn by account holder. Write method display which will display name and Balanceamt. Your application should create array of account class and store 3 object. Display name and balance
Create console application and use this class library. Create at least two object of account class and deposit and withdraw money.*/

namespace ConsoleApp_uselib_A4
{
    class Program
    {
        static void Main(string[] args)
        {
            Account[] acc = new Account[3];
            acc[0] = new Account("Tom", 2000);
            acc[1] = new Account("Todd", 4000);
            acc[2] = new Account("John", 6000);
            Console.WriteLine("Original Data: ");
            for (int i = 0; i < 3; i++)
                Console.WriteLine(acc[i].Display());
            
            Console.WriteLine("\nDepositing 200 each....");
            for (int i = 0; i < 3; i++)
            {
                acc[i].Deposite(100*2);
                Console.WriteLine(acc[i].Display());
            }
            Console.WriteLine("\nWidrawing 100 each....");
            for (int i = 0; i < 3; i++)
            {
                acc[i].Withdraw(100);
                Console.WriteLine(acc[i].Display());
            }
                Console.ReadLine();
        }
    }
}
