using System;
using ClassLib_employee_A3;
/*Create a class Employee having private instance member Id, Name Salary, netsalary.  
 * Id should be generated by application 
 * Create method calculate_netsalary who’s job is to deduct 10% of TDS. Declare TDS as static variable. 
 * Write method display which will display name and netsalary. 
 * This application will be classlibrary. Declare const int maxemp=3 ie. You can have only 3 employee.
Also declare const int maxsal=50000. Use this for validation in constructor if you try to create object with salary 80000 it should display error
Create console application and use this class library. Create at least two object of Employee class */

namespace ConsoleApp_uselib_Employee_A3
{
    class Program
    {
        static void Main(string[] args)
        {
           Employee e1 = new Employee("Tom", 30000);
           // Employee e1 = new Employee("Tom", 51000);   Invalid Salary
            Employee e2 = new Employee("Todd", 40000);
            Employee e3 = new Employee("John", 20000);
            //Employee e4 = new Employee("Jerry", 15000); //maxObject reached 

            Console.WriteLine("\nEmployee Deatils...\n");
            Console.WriteLine(e1.Display());
            Console.WriteLine(e2.Display());
            Console.WriteLine(e3.Display());

            Console.ReadLine();
        }
    }
}
